{
 "title": "Recommendations",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Количество персональных рекомендаций",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_personal_recommendation_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество стандартных рекомендаций",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_default_recommendation_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество ошибок при выдаче рекомендаций",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_error_recommendation_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кол-во запросов в минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_requests_total{handler=\"/recommendations_offline\", instance=\"recs_app:8081\", job=\"scrapping-recs-app\", method=\"POST\", status=\"2xx\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребление RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}